server:
  port: 1112
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
Spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
        enabled: true