server:
  port: 1112
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
Spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  rabbitmq:
    password: guest
    username: guest
    host: 192.168.101.173
    port: 5672
  redis:
    host: localhost
    port: 6379
    jedis:
      pool:
        max-idle: 300
        max-active: 600
    thymeleaf: content-type=text/html
  mongodb:
    uri: mongodb://name:password@//localhost:27017/test